default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: foosball-funball_development
test:
  <<: *default
  database: foosball-funball_test
production:
  <<: *default
  database: foosball-funball_production
  username: foosball-funball
  password: <%= ENV['FOOSBALL-FUNBALL_DATABASE_PASSWORD'] %>
